export const FINANCE_CONSTANTS = Object.freeze({
  CURRENCY: Object.freeze({
    INR: "INR",
    USD: "USD",
    EUR: "EUR",
    AED: "AED",
    SGD: "SGD",
    GBP: "GBP",
  }),

  PAYMENT_MODES: Object.freeze({
    CASH: "CASH",
    BANK_TRANSFER: "BANK_TRANSFER",
    CARD: "CARD",
    UPI: "UPI",
    CHEQUE: "CHEQUE",
  }),

  PAYMENT_STATUS: Object.freeze({
    PENDING: "PENDING",
    PARTIAL: "PARTIAL",
    PAID: "PAID",
    FAILED: "FAILED",
    CANCELLED: "CANCELLED",
    REFUNDED: "REFUNDED",
  }),

  INVOICE_STATUS: Object.freeze({
    DRAFT: "DRAFT",
    ISSUED: "ISSUED",
    SENT: "SENT",
    PARTIALLY_PAID: "PARTIALLY_PAID",
    PAID: "PAID",
    OVERDUE: "OVERDUE",
    CANCELLED: "CANCELLED",
  }),

  INVOICE_TYPES: Object.freeze({
    TAX_INVOICE: "TAX_INVOICE",
    PROFORMA: "PROFORMA",
    COMMERCIAL: "COMMERCIAL",
    CREDIT_NOTE: "CREDIT_NOTE",
    DEBIT_NOTE: "DEBIT_NOTE",
  }),

  TRANSACTION_TYPES: Object.freeze({
    RECEIVABLE: "RECEIVABLE",
    PAYABLE: "PAYABLE",
    RECEIPT: "RECEIPT",
    PAYMENT: "PAYMENT",
    REFUND: "REFUND",
    ADJUSTMENT: "ADJUSTMENT",
  }),

  CHARGE_TYPES: Object.freeze({
    FREIGHT: "FREIGHT",
    HANDLING: "HANDLING",
    DOCUMENTATION: "DOCUMENTATION",
    CUSTOMS: "CUSTOMS",
    WAREHOUSE: "WAREHOUSE",
    TRANSPORT: "TRANSPORT",
    DELIVERY: "DELIVERY",
    INSURANCE: "INSURANCE",
    PACKING: "PACKING",
    STORAGE: "STORAGE",
    OTHER: "OTHER",
  }),

  TAX: Object.freeze({
    GST: "GST",
    IGST: "IGST",
    CGST: "CGST",
    SGST: "SGST",
    VAT: "VAT",
    OTHER: "OTHER",
  }),

  ACCOUNT_TYPES: Object.freeze({
    ASSET: "ASSET",
    LIABILITY: "LIABILITY",
    EQUITY: "EQUITY",
    REVENUE: "REVENUE",
    EXPENSE: "EXPENSE",
  }),

  COST_TYPES: Object.freeze({
    DIRECT: "DIRECT",
    INDIRECT: "INDIRECT",
    PROVISIONAL: "PROVISIONAL",
    ACTUAL: "ACTUAL",
  }),

  JOURNAL_STATUS: Object.freeze({
    DRAFT: "DRAFT",
    POSTED: "POSTED",
    REVERSED: "REVERSED",
    CANCELLED: "CANCELLED",
  }),

  RECONCILIATION_STATUS: Object.freeze({
    PENDING: "PENDING",
    IN_PROGRESS: "IN_PROGRESS",
    RECONCILED: "RECONCILED",
    DISCREPANCY: "DISCREPANCY",
  }),

  SETTLEMENT_STATUS: Object.freeze({
    PENDING: "PENDING",
    PARTIALLY_SETTLED: "PARTIALLY_SETTLED",
    SETTLED: "SETTLED",
    CANCELLED: "CANCELLED",
  }),

  ROUNDING: Object.freeze({
    DECIMAL_PLACES: 2,
    MINOR_UNIT_FACTOR: 100,
  }),

  NUMBERING: Object.freeze({
    INVOICE_PREFIX: "INV",
    RECEIPT_PREFIX: "RCT",
    PAYMENT_PREFIX: "PAY",
    CREDIT_NOTE_PREFIX: "CN",
    DEBIT_NOTE_PREFIX: "DN",
    JOURNAL_PREFIX: "JV",
  }),

  EVENTS: Object.freeze({
    INVOICE_CREATED: "invoice:created",
    INVOICE_UPDATED: "invoice:updated",
    INVOICE_APPROVED: "invoice:approved",
    INVOICE_SENT: "invoice:sent",
    INVOICE_CANCELLED: "invoice:cancelled",

    PAYMENT_CREATED: "payment:created",
    PAYMENT_UPDATED: "payment:updated",
    PAYMENT_APPROVED: "payment:approved",
    PAYMENT_CANCELLED: "payment:cancelled",

    RECEIPT_CREATED: "receipt:created",
    RECEIPT_UPDATED: "receipt:updated",

    JOURNAL_POSTED: "journal:posted",
    JOURNAL_REVERSED: "journal:reversed",

    COST_CREATED: "cost:created",
    COST_UPDATED: "cost:updated",

    SETTLEMENT_CREATED: "settlement:created",
    SETTLEMENT_COMPLETED: "settlement:completed",

    RECONCILIATION_COMPLETED: "reconciliation:completed",
  }),

  ERROR_CODES: Object.freeze({
    INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
    INVOICE_ALREADY_EXISTS: "INVOICE_ALREADY_EXISTS",
    INVALID_INVOICE_STATUS: "INVALID_INVOICE_STATUS",
    INVOICE_ALREADY_CANCELLED: "INVOICE_ALREADY_CANCELLED",

    PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
    PAYMENT_ALREADY_EXISTS: "PAYMENT_ALREADY_EXISTS",
    INVALID_PAYMENT_STATUS: "INVALID_PAYMENT_STATUS",
    PAYMENT_AMOUNT_INVALID: "PAYMENT_AMOUNT_INVALID",

    RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",

    JOURNAL_NOT_FOUND: "JOURNAL_NOT_FOUND",
    JOURNAL_ALREADY_POSTED: "JOURNAL_ALREADY_POSTED",
    JOURNAL_ALREADY_REVERSED: "JOURNAL_ALREADY_REVERSED",
    JOURNAL_BALANCE_MISMATCH: "JOURNAL_BALANCE_MISMATCH",

    COST_NOT_FOUND: "COST_NOT_FOUND",
    INVALID_COST_TYPE: "INVALID_COST_TYPE",

    SETTLEMENT_NOT_FOUND: "SETTLEMENT_NOT_FOUND",
    SETTLEMENT_ALREADY_COMPLETED: "SETTLEMENT_ALREADY_COMPLETED",

    RECONCILIATION_NOT_FOUND: "RECONCILIATION_NOT_FOUND",
    RECONCILIATION_DISCREPANCY: "RECONCILIATION_DISCREPANCY",

    INVALID_CURRENCY: "INVALID_CURRENCY",
    INVALID_PAYMENT_MODE: "INVALID_PAYMENT_MODE",
    INVALID_AMOUNT: "INVALID_AMOUNT",
    INVALID_TAX_AMOUNT: "INVALID_TAX_AMOUNT",
  }),
} as const);

export type FinanceCurrency =
  (typeof FINANCE_CONSTANTS.CURRENCY)[keyof typeof FINANCE_CONSTANTS.CURRENCY];

export type PaymentMode =
  (typeof FINANCE_CONSTANTS.PAYMENT_MODES)[keyof typeof FINANCE_CONSTANTS.PAYMENT_MODES];

export type PaymentStatus =
  (typeof FINANCE_CONSTANTS.PAYMENT_STATUS)[keyof typeof FINANCE_CONSTANTS.PAYMENT_STATUS];

export type InvoiceStatus =
  (typeof FINANCE_CONSTANTS.INVOICE_STATUS)[keyof typeof FINANCE_CONSTANTS.INVOICE_STATUS];

export type InvoiceType =
  (typeof FINANCE_CONSTANTS.INVOICE_TYPES)[keyof typeof FINANCE_CONSTANTS.INVOICE_TYPES];

export type TransactionType =
  (typeof FINANCE_CONSTANTS.TRANSACTION_TYPES)[keyof typeof FINANCE_CONSTANTS.TRANSACTION_TYPES];

export type ChargeType =
  (typeof FINANCE_CONSTANTS.CHARGE_TYPES)[keyof typeof FINANCE_CONSTANTS.CHARGE_TYPES];

export type TaxType =
  (typeof FINANCE_CONSTANTS.TAX)[keyof typeof FINANCE_CONSTANTS.TAX];

export type AccountType =
  (typeof FINANCE_CONSTANTS.ACCOUNT_TYPES)[keyof typeof FINANCE_CONSTANTS.ACCOUNT_TYPES];

export type CostType =
  (typeof FINANCE_CONSTANTS.COST_TYPES)[keyof typeof FINANCE_CONSTANTS.COST_TYPES];

export type JournalStatus =
  (typeof FINANCE_CONSTANTS.JOURNAL_STATUS)[keyof typeof FINANCE_CONSTANTS.JOURNAL_STATUS];

export type ReconciliationStatus =
  (typeof FINANCE_CONSTANTS.RECONCILIATION_STATUS)[keyof typeof FINANCE_CONSTANTS.RECONCILIATION_STATUS];

export type SettlementStatus =
  (typeof FINANCE_CONSTANTS.SETTLEMENT_STATUS)[keyof typeof FINANCE_CONSTANTS.SETTLEMENT_STATUS];

export type FinanceEvent =
  (typeof FINANCE_CONSTANTS.EVENTS)[keyof typeof FINANCE_CONSTANTS.EVENTS];

export type FinanceErrorCode =
  (typeof FINANCE_CONSTANTS.ERROR_CODES)[keyof typeof FINANCE_CONSTANTS.ERROR_CODES];